<script setup lang="ts">
import HeadingSmall from '@/components/HeadingSmall.vue';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { FormField, FormItem } from '@/components/ui/form';
import { Label } from '@/components/ui/label';
import AppLayout from '@/layouts/AppLayout.vue';
import SettingsLayout from '@/layouts/settings/Layout.vue';
import { type BreadcrumbItem } from '@/types';
import { Head, router } from '@inertiajs/vue3';
import { toTypedSchema } from '@vee-validate/zod';
import { useForm } from 'vee-validate';
import { watch } from 'vue';
import * as z from 'zod';
// Route will be auto-generated by wayfinder
const edit = () => ({ url: '/settings/registration' });

interface Props {
    registration_enabled?: boolean;
}

const props = defineProps<Props>();

const formSchema = toTypedSchema(
    z.object({
        registration_enabled: z.boolean().default(false),
    }),
);

const { handleSubmit, resetForm, setFieldValue } = useForm({
    validationSchema: formSchema,
    initialValues: {
        registration_enabled: props.registration_enabled ?? false,
    },
});

// Update form when props change (after successful save/redirect)
watch(
    () => props.registration_enabled,
    (newValue) => {
        setFieldValue('registration_enabled', newValue ?? false);
        resetForm({ values: { registration_enabled: newValue ?? false } });
    },
);

const onSubmit = handleSubmit((values) => {
    router.patch(edit().url, values, {
        preserveScroll: true,
        onSuccess: () => {
            // Form will be updated via watch when props change
        },
    });
});

const breadcrumbItems: BreadcrumbItem[] = [
    {
        title: 'Registration settings',
        href: edit().url,
    },
];
</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbItems">
        <Head title="Registration settings" />

        <SettingsLayout>
            <div class="space-y-6">
                <HeadingSmall
                    title="Registration settings"
                    description="Control whether users can register new accounts"
                />

                <form class="space-y-6" @submit.prevent="onSubmit">
                    <FormField
                        v-slot="{ value, handleChange, error }"
                        type="checkbox"
                        name="registration_enabled"
                        label=""
                        class="!grid-cols-1"
                    >
                        <FormItem
                            class="flex flex-row items-start space-y-0 gap-x-3 rounded-md border p-4 shadow"
                        >
                            <Checkbox
                                id="registration_enabled"
                                :model-value="value"
                                @update:model-value="handleChange"
                            />
                            <div class="space-y-1 leading-none">
                                <Label
                                    for="registration_enabled"
                                    class="cursor-pointer text-sm leading-none font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                                >
                                    Enable user registration
                                </Label>
                                <p class="text-sm text-muted-foreground">
                                    When enabled, users can create new accounts.
                                    When disabled, registration is only allowed
                                    if no users exist in the system (for initial
                                    setup).
                                </p>
                                <p
                                    v-if="error"
                                    class="mt-1 text-sm text-destructive"
                                >
                                    {{ error }}
                                </p>
                            </div>
                        </FormItem>
                    </FormField>

                    <div class="flex items-center gap-4">
                        <Button type="submit">Save</Button>

                        <Transition
                            enter-active-class="transition ease-in-out"
                            enter-from-class="opacity-0"
                            leave-active-class="transition ease-in-out"
                            leave-to-class="opacity-0"
                        >
                            <p
                                v-show="($page.props as any).flash?.success"
                                class="text-sm text-neutral-600"
                            >
                                Saved.
                            </p>
                        </Transition>
                    </div>
                </form>
            </div>
        </SettingsLayout>
    </AppLayout>
</template>
